import { builtinModules } from 'node:module';
import process from 'node:process';
import esbuild from 'esbuild';

const production = process.argv[2] === 'production';

const context = await esbuild.context({
	banner: {
		js: `/*
This file is generated by esbuild.
Read the source at https://github.com/woosal1337/knap-templates.
*/`,
	},
	bundle: true,
	entryPoints: ['src/main.ts'],
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules,
	],
	format: 'cjs',
	logLevel: 'info',
	minify: production,
	outfile: 'main.js',
	sourcemap: production ? false : 'inline',
	target: 'es2021',
	treeShaking: true,
});

if (production) {
	await context.rebuild();
	await context.dispose();
}
else {
	await context.watch();
}
